# Generated by Django 2.2.6 on 2021-10-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20211028_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время публикации поста', verbose_name='Дата и время публикации поста'),
        ),
    ]
